src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $username;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'string', length: 50)]
    private $DisplayName;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Post::class)]
    private $posts;

    public function __construct()
    {
        $this->posts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getDisplayName(): ?string
    {
        return $this->DisplayName;
    }

    public function setDisplayName(string $DisplayName): self
    {
        $this->DisplayName = $DisplayName;

        return $this;
    }

    public function setAdmin(bool $isAdmin): self
    {
        if ($isAdmin && !$this->isAdmin()) {
            $this->roles[] = "ROLE_ADMIN";
        } elseif (!$isAdmin) {
            $this->roles = array_diff($this->roles, array('ROLE_ADMIN'));
        }

        return $this;
    }

    public function isAdmin(): bool
    {
        return in_array("ROLE_ADMIN", $this->roles, true);
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection<int, Post>
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Post $post): self
    {
        if (!$this->posts->contains($post)) {
            $this->posts[] = $post;
            $post->setUser($this);
        }

        return $this;
    }

    public function removePost(Post $post): self
    {
        if ($this->posts->removeElement($post)) {
            // set the owning side to null (unless already changed)
            if ($post->getUser() === $this) {
                $post->setUser(null);
            }
        }

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('username')
            ->add('roles')
            ->add('password')
            ->add('DisplayName')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/user')]
class UserController extends AbstractController
{
    #[Route('/', name: 'app_user_index', methods: ['GET'])]
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    #[Route('/{id}', name: 'app_user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, int $id, UserRepository $userRepository): Response
    {
        $user = new User();
        if ($id > 0) {
            $user = $userRepository->find($id);
        }

        if ($request->getMethod() == "POST") {
            $user->setUsername($request->request->get("username"));
            $user->setDisplayName($request->request->get("display-name"));

            $isAdmin = $request->request->get("is-admin");
            $user->setAdmin($isAdmin === "on");

            if (!$user->getId()) {
                // new user set password
                $password = $request->request->get("password");
                $passwordRepeat = $request->request->get("password-repeat");

                if ($password != $passwordRepeat) {
                    return $this->render('user/edit.html.twig', [
                        'user' => $user,
                        'error' => "Die Passwörter sind nicht gleich!",
                    ]);
                }

                $hashedPassword = $userRepository->hashPassword($user, $password);
                $user->setPassword($hashedPassword);
            }


            $userRepository->add($user);
            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/delete/{id}', name: 'app_user_delete', methods: ['POST'] )]
    public function delete(Request $request, User $user, UserRepository $userRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $userRepository->remove($user);
        }

        return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    {% if user.id %}
        <h1>Benutzer bearbeiten</h1>
    {% else %}
        <h1>neuen Benutzer erstellen</h1>
    {% endif %}

    <form class="form block" id="edit-form" action="{{ path('app_user_edit', {'id': user.id ?: 0 }) }}" method="post">
        <div class="field">
            <label class="label">Username</label>
            <div class="control">
                <input name="username" required="required" class="input" type="text" placeholder="Username" value="{{ user.username }}">
            </div>
        </div>

        <div class="field">
            <label class="label">Anzeigename</label>
            <div class="control">
                <input name="display-name" required="required" class="input" type="text" placeholder="Anzeigename" value="{{ user.displayName }}">
            </div>
        </div>

        <div class="field">
            <label class="label">Admin</label>
            <div class="control">
                <label class="checkbox">
                    <input type="checkbox" name="is-admin" {% if user.admin %} checked="checked" {% endif %}>
                    Ist Admin
                </label>
            </div>
        </div>

        {% if not user.id %}
            <div class="field">
                <label class="label">Passwort</label>
                <div class="control">
                    <input name="password" required="required" minlength="4" class="input" type="password" placeholder="Passwort">
                </div>
            </div>

            <div class="field">
                <label class="label">Passwort wiederholen</label>
                <div class="control">
                    <input name="password-repeat" required="required" minlength="4" class="input" type="password" placeholder="Passwort wiederholen">
                </div>
            </div>
        {% endif %}

        {% if error is defined %}
            <div class="notification is-danger">
                {{ error }}
            </div>
        {%  endif %}

    </form>

    <div class="block">
        <a class="button" href="{{ path('app_user_index') }}">Abbrechen</a>
        {% if user.id %}
            <form hidden="hidden" id="delete-form" method="post" action="{{ path('app_user_delete', {'id': user.id}) }}"
                  onsubmit="return confirm('Soll der Benutzer \'{{ user.username }}\' wirklich gelöscht werden?');">
                <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">

            </form>
            <button type="submit" form="delete-form" class="button">Löschen</button>
        {% endif %}

        <button type="submit" form="edit-form" class="button is-primary is-pulled-right" >Speichern</button>
    </div>



{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <div class="columns">
        <div class="column">
            <h1>Benutzer</h1>
        </div>
        <div class="column">
            <a class="button is-primary is-pulled-right" href="{{ path('app_user_edit', {'id': 0}) }}">Neuer Benutzer</a>
        </div>

    </div>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Benutzername</th>
                <th class="has-text-centered">Admin</th>
                <th>Anzeigename</th>
                <th class="has-text-centered">Bearbeiten</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.username }}</td>
                <td class="has-text-centered">
                    <span class="icon is-small"><svg>
                    {% if user.admin %}
                        <use xlink:href="{{ asset('images/regular.svg#check-square') }}"></use>
                    {% else %}
                        <use xlink:href="{{ asset('images/regular.svg#square') }}"></use>
                    {% endif %}
                    </svg></span>
                </td>
                <td>{{ user.DisplayName }}</td>
                <td class="has-text-centered">
                    <a class="button is-small" href="{{ path('app_user_edit', {'id': user.id}) }}">bearbeiten</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}